version: '3.1'

services:

  app:
    container_name: app_montine
    image: 720157/montine
    environment:
      DB_HOST: localhost:3306
      DB_USER: ${DATASOURCE_USERNAME}
      DB_PASSWORD: ${DATASOURCE_PASSWORD}
      DB_NAME: ${DATASOURCE_DATABASE}
    ports:
    - "8008:8007"
  db:
    container_name: mysql_container
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DB: ${DATASOURCE_DATABASE}
      MYSQL_ROOT_PASSWORD: password
    ports:
    - "3307:3306"